services:
  mi-postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas123
      POSTGRES_DB: atlas_bank
  mi-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: otra_db